server:
  port: 9006
spring:
  application:
    name: unicorn_roast
  data:
    mongodb:
      host: 39.105.97.53
      database: unicorn_roast

  redis:
    host: 39.105.97.53
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true