server: 
  port: 9005
spring: 
  application:  
    name: unicorn_activity #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.97.53:3306/unicorn_activity?characterEncoding=UTF8&useSSL=false
    username: root
    password: root1234
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true