server:
  port: 9007
spring:
  application:
    name: unicorn-search
  data:
    elasticsearch:
      cluster-nodes: 39.105.97.53:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true