server:
  port: 12000
spring:
  application:
    name: unicorn-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/unicorn-w/unicorn_config.git
      enabled: true
  rabbitmq:
    host: 39.105.97.53
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh